name: PR Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Scala and SBT
        uses: olafurpg/setup-scala@v14

      - name: Build project
        run: sbt fullOptJS

      - name: Run tests
        run: sbt test
